### PR TITLE
Fix compose sample previews.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
They were broken by the beta upgrade in 511fe880716655d408cf981b23c35a0b3ea73dc5 (#341).

cc @SalvatoreT

### CODE REVIEW

**Review by rjrjr — APPROVED** [review]

**Comment by SalvatoreT** [comment]
Thank you!

**Comment by SalvatoreT** [comment]
This seems like a flakey error.

```
FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/cli/common/PropertiesKt
> org.jetbrains.kotlin.cli.common.PropertiesKt

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/cli/common/PropertiesKt
	at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:83)
	at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:50)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
        ...
```

**Comment by zach-klippenstein** [comment]
Probably, rerunning anyway but I'll merge this today regardless.
